name: Windows build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - shell: pwsh
        run: .\build.ps1 -Version "1.0.0-ci.${{ github.run_number }}"
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
        with:
          name: DynamicResolutionSwitcher-${{ github.sha }}
          path: release/
          if-no-files-found: error
